name: Submit Your PS5 Pro 30th
description: Add your console to the public collector registry!
title: "Entry: #XXXX - YourName"
labels: ["submission"]
body:
  - type: input
    id: number
    attributes:
      label: Console Number
      description: Enter your PS5 Pro 30th Anniversary Edition number (e.g., 00874)
      placeholder: "00874"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name or Alias
      description: Optional display name or nickname
      placeholder: "PlayStationBro77"
    validations:
      required: false

  - type: input
    id: discord
    attributes:
      label: Discord (optional)
      placeholder: "@YourName#1234"
    validations:
      required: false

  - type: input
    id: psn
    attributes:
      label: PSN ID (optional)
      placeholder: "banana_jones"
    validations:
      required: false

  - type: input
    id: twitter
    attributes:
      label: Twitter/X (optional)
      placeholder: "@banana4life"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes or Story (optional)
      description: How did you get it? Where are you from? Any cool story?
      placeholder: "Won this in a Twitch giveaway!"
    validations:
      required: false

  - type: textarea
    id: image-upload
    attributes:
      label: Upload a Photo of Your Console
      description: Drag and drop a photo here showing your PS5 Pro number clearly. If it doesn't work, you can also upload it in the comment section after submitting.
      placeholder: Drag image here or upload via comment
    validations:
      required: true
