name: Submit Your PS5 Pro 30th
description: Add your unit to the official community registry
title: "Entry: #XXXX - YourName"
labels: ["submission"]
body:
  - type: input
    id: number
    attributes:
      label: Console Number
      description: Enter your PS5 Pro 30th serial number (e.g., 00874)
      placeholder: "00874"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name or Alias
      description: Optional display name or nickname
      placeholder: "PlayStationBro77"
    validations:
      required: false

  - type: input
    id: discord
    attributes:
      label: Discord (optional)
      description: Share your Discord tag
      placeholder: "@YourName#1234"
    validations:
      required: false

  - type: input
    id: psn
    attributes:
      label: PSN ID (optional)
      description: Add your PlayStation Network username
      placeholder: "banana_jones"
    validations:
      required: false

  - type: input
    id: twitter
    attributes:
      label: Twitter/X (optional)
      description: Add your Twitter/X handle
      placeholder: "@banana4life"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes or Story
      description: Anything else you wanna share? (e.g., how you got it, country, fun fact, etc.)
      placeholder: "Won this in a Twitch giveaway!"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Please upload a photo below that clearly shows your console's number. Submissions without a clear image may be rejected.**

