name: Update PS5 Pro Registry Data

on:
  push:
    branches:
      - main  # or your default branch
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and parse GitHub Issues with label 'approved'
        run: |
          mkdir -p data

          curl -s -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=approved" > issues.json

          jq '[.[] | {
            number: (.body | capture("Console Number\\s*:?\\s*(?<val>[0-9]+)")?.val // "unknown"),
            name: (.body | capture("Name or Alias\\s*:?\\s*(?<val>.+)")?.val // "Anonymous"),
            notes: (.body | capture("Notes or Story.*?\\n(?<val>.*?)\\n")?.val // ""),
            socials: {
              discord: (.body | capture("Discord.*?\\n(?<val>.*?)\\n")?.val // ""),
              psn: (.body | capture("PSN.*?\\n(?<val>.*?)\\n")?.val // ""),
              twitter: (.body | capture("Twitter.*?\\n(?<val>.*?)\\n")?.val // "")
            }
          }]' issues.json > data/entries.json

      - name: Commit updated entries
        run: |
          git config user.name "ps5-bot"
          git config user.email "bot@ps5pro.com"
          git add data/entries.json
          git commit -m "📃 Auto-update registry data [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
